-- Adds the nocturnal-trips and explored-routes achievement categories.
-- Canonical journey grouping remains the source for journey starts; eligible
-- stages and full journeys are both included as explored directed ODs.
create or replace function public.refresh_profile_achievement_progress(
  p_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  stage record;
  has_current boolean := false;
  current_started_at timestamptz;
  current_ended_at timestamptz;
  current_origin_id text;
  current_origin_name text;
  current_destination_id text;
  current_destination_name text;
  current_origin_lat double precision;
  current_origin_lon double precision;
  current_destination_lat double precision;
  current_destination_lon double precision;
  current_single_distance double precision;
  current_stage_count integer := 0;
  journey_duration_seconds double precision;
  journey_distance double precision;
  origin_key text;
  destination_key text;
  pit_stop_progress integer := 0;
  fast_trip_progress integer := 0;
  favorite_station_progress integer := 0;
  night_trip_progress integer := 0;
  explored_route_progress integer := 0;
begin
  create temporary table if not exists achievement_progress_station_usage (
    station_key text primary key,
    usage_count integer not null
  ) on commit drop;
  truncate table pg_temp.achievement_progress_station_usage;

  create temporary table if not exists achievement_progress_route_usage (
    route_key text primary key,
    first_seen_at timestamptz not null
  ) on commit drop;
  truncate table pg_temp.achievement_progress_route_usage;

  create temporary table if not exists achievement_progress_night_events (
    event_index bigint generated by default as identity,
    ended_at timestamptz not null
  ) on commit drop;
  truncate table pg_temp.achievement_progress_night_events;

  insert into pg_temp.achievement_progress_route_usage (route_key, first_seen_at)
  select distinct on (eligible_trip.route_key)
    eligible_trip.route_key, eligible_trip.started_at
  from (
    select trip.*,
      concat_ws('||',
        coalesce(nullif(public.bicimad_public_station_code(
          trip.origin_station_id, trip.origin_station_name), ''),
          'id:' || nullif(btrim(trip.origin_station_id), '')),
        coalesce(nullif(public.bicimad_public_station_code(
          trip.destination_station_id, trip.destination_station_name), ''),
          'id:' || nullif(btrim(trip.destination_station_id), ''))
      ) as route_key
    from public.trips trip
    where trip.user_id = p_user_id
      and trip.duration_seconds > 0
      and trip.origin_station_id <> trip.destination_station_id
  ) eligible_trip
  where eligible_trip.route_key is not null
  order by eligible_trip.route_key, eligible_trip.started_at, eligible_trip.id;
  for stage in
    select
      trip.id,
      trip.origin_station_id,
      trip.origin_station_name,
      trip.destination_station_id,
      trip.destination_station_name,
      trip.started_at,
      trip.started_at + trip.duration_seconds * interval '1 second' as ended_at,
      trip.origin_latitude,
      trip.origin_longitude,
      trip.destination_latitude,
      trip.destination_longitude,
      trip.direct_distance_meters
    from public.trips trip
    where trip.user_id = p_user_id
      and trip.duration_seconds > 0
      and trip.origin_station_id <> trip.destination_station_id
    order by trip.started_at, trip.id
  loop
    if not has_current then
      has_current := true;

      current_started_at := stage.started_at;
      current_ended_at := stage.ended_at;
      current_origin_id := stage.origin_station_id;
      current_origin_name := stage.origin_station_name;
      current_destination_id := stage.destination_station_id;
      current_destination_name := stage.destination_station_name;
      current_origin_lat := stage.origin_latitude;
      current_origin_lon := stage.origin_longitude;
      current_destination_lat := stage.destination_latitude;
      current_destination_lon := stage.destination_longitude;
      current_single_distance := stage.direct_distance_meters;
      current_stage_count := 1;
    elsif extract(epoch from stage.started_at - current_ended_at) between 0 and 119
      and current_destination_id = stage.origin_station_id
      and current_origin_id <> stage.destination_station_id then
      current_ended_at := stage.ended_at;
      current_destination_id := stage.destination_station_id;
      current_destination_name := stage.destination_station_name;
      current_destination_lat := stage.destination_latitude;
      current_destination_lon := stage.destination_longitude;
      current_stage_count := current_stage_count + 1;
    else
      pit_stop_progress := pit_stop_progress
        + greatest(current_stage_count - 1, 0);
      journey_duration_seconds := extract(
        epoch from current_ended_at - current_started_at
      );
      journey_distance := case
        when current_stage_count = 1 then current_single_distance
        when current_origin_lat is not null
          and current_origin_lon is not null
          and current_destination_lat is not null
          and current_destination_lon is not null then
          2 * 6371000 * asin(sqrt(least(1.0,
            power(sin(radians(current_destination_lat - current_origin_lat) / 2), 2)
            + cos(radians(current_origin_lat))
              * cos(radians(current_destination_lat))
              * power(sin(radians(current_destination_lon - current_origin_lon) / 2), 2)
          )))
        else null
      end;
      if journey_distance is not null
        and journey_duration_seconds > 0
        and journey_distance / journey_duration_seconds * 3.6 > 14.000000001 then
        fast_trip_progress := fast_trip_progress + 1;
      end if;

      origin_key := coalesce(
        nullif(public.bicimad_public_station_code(
          current_origin_id,
          current_origin_name
        ), ''),
        'name:' || nullif(lower(regexp_replace(
          public.bicimad_station_display_name(
            current_origin_id,
            current_origin_name
          ),
          '[^[:alnum:]]+',
          '',
          'g'
        )), ''),
        'id:' || nullif(btrim(current_origin_id), '')
      );
      destination_key := coalesce(
        nullif(public.bicimad_public_station_code(
          current_destination_id,
          current_destination_name
        ), ''),
        'name:' || nullif(lower(regexp_replace(
          public.bicimad_station_display_name(
            current_destination_id,
            current_destination_name
          ),
          '[^[:alnum:]]+',
          '',
          'g'
        )), ''),
        'id:' || nullif(btrim(current_destination_id), '')
      );
      if origin_key is not null then
        insert into pg_temp.achievement_progress_station_usage (
          station_key,
          usage_count
        ) values (origin_key, 1)
        on conflict (station_key) do update set
          usage_count = achievement_progress_station_usage.usage_count + 1;
      end if;
      if destination_key is not null then
        insert into pg_temp.achievement_progress_station_usage (
          station_key,
          usage_count
        ) values (destination_key, 1)
        on conflict (station_key) do update set
          usage_count = achievement_progress_station_usage.usage_count + 1;
      end if;

      if extract(hour from current_started_at at time zone 'Europe/Madrid') between 0 and 5 then
        insert into pg_temp.achievement_progress_night_events (ended_at)
        values (current_ended_at);
        night_trip_progress := night_trip_progress + 1;
      end if;
      origin_key := coalesce(
        nullif(public.bicimad_public_station_code(
          current_origin_id, current_origin_name), ''),
        'id:' || nullif(btrim(current_origin_id), '')
      );
      destination_key := coalesce(
        nullif(public.bicimad_public_station_code(
          current_destination_id, current_destination_name), ''),
        'id:' || nullif(btrim(current_destination_id), '')
      );
      if origin_key is not null and destination_key is not null
        and origin_key <> destination_key then
        insert into pg_temp.achievement_progress_route_usage (
          route_key, first_seen_at
        ) values (
          origin_key || '||' || destination_key, current_started_at
        ) on conflict (route_key) do update set
          first_seen_at = least(
            achievement_progress_route_usage.first_seen_at,
            excluded.first_seen_at
          );
      end if;
      current_started_at := stage.started_at;
      current_ended_at := stage.ended_at;
      current_origin_id := stage.origin_station_id;
      current_origin_name := stage.origin_station_name;
      current_destination_id := stage.destination_station_id;
      current_destination_name := stage.destination_station_name;
      current_origin_lat := stage.origin_latitude;
      current_origin_lon := stage.origin_longitude;
      current_destination_lat := stage.destination_latitude;
      current_destination_lon := stage.destination_longitude;
      current_single_distance := stage.direct_distance_meters;
      current_stage_count := 1;
    end if;
  end loop;

  if has_current then
    pit_stop_progress := pit_stop_progress
      + greatest(current_stage_count - 1, 0);
    journey_duration_seconds := extract(
      epoch from current_ended_at - current_started_at
    );
    journey_distance := case
      when current_stage_count = 1 then current_single_distance
      when current_origin_lat is not null
        and current_origin_lon is not null
        and current_destination_lat is not null
        and current_destination_lon is not null then
        2 * 6371000 * asin(sqrt(least(1.0,
          power(sin(radians(current_destination_lat - current_origin_lat) / 2), 2)
          + cos(radians(current_origin_lat))
            * cos(radians(current_destination_lat))
            * power(sin(radians(current_destination_lon - current_origin_lon) / 2), 2)
        )))
      else null
    end;
    if journey_distance is not null
      and journey_duration_seconds > 0
      and journey_distance / journey_duration_seconds * 3.6 > 14.000000001 then
      fast_trip_progress := fast_trip_progress + 1;
    end if;

    origin_key := coalesce(
      nullif(public.bicimad_public_station_code(
        current_origin_id,
        current_origin_name
      ), ''),
      'name:' || nullif(lower(regexp_replace(
        public.bicimad_station_display_name(
          current_origin_id,
          current_origin_name
        ),
        '[^[:alnum:]]+',
        '',
        'g'
      )), ''),
      'id:' || nullif(btrim(current_origin_id), '')
    );
    destination_key := coalesce(
      nullif(public.bicimad_public_station_code(
        current_destination_id,
        current_destination_name
      ), ''),
      'name:' || nullif(lower(regexp_replace(
        public.bicimad_station_display_name(
          current_destination_id,
          current_destination_name
        ),
        '[^[:alnum:]]+',
        '',
        'g'
      )), ''),
      'id:' || nullif(btrim(current_destination_id), '')
    );
    if origin_key is not null then
      insert into pg_temp.achievement_progress_station_usage (
        station_key,
        usage_count
      ) values (origin_key, 1)
      on conflict (station_key) do update set
        usage_count = achievement_progress_station_usage.usage_count + 1;
    end if;
    if destination_key is not null then
      insert into pg_temp.achievement_progress_station_usage (
        station_key,
        usage_count
      ) values (destination_key, 1)
      on conflict (station_key) do update set
        usage_count = achievement_progress_station_usage.usage_count + 1;
    end if;
  end if;
    if extract(hour from current_started_at at time zone 'Europe/Madrid') between 0 and 5 then
      insert into pg_temp.achievement_progress_night_events (ended_at)
      values (current_ended_at);
      night_trip_progress := night_trip_progress + 1;
    end if;
    origin_key := coalesce(
      nullif(public.bicimad_public_station_code(
        current_origin_id, current_origin_name), ''),
      'id:' || nullif(btrim(current_origin_id), '')
    );
    destination_key := coalesce(
      nullif(public.bicimad_public_station_code(
        current_destination_id, current_destination_name), ''),
      'id:' || nullif(btrim(current_destination_id), '')
    );
    if origin_key is not null and destination_key is not null
      and origin_key <> destination_key then
      insert into pg_temp.achievement_progress_route_usage (
        route_key, first_seen_at
      ) values (
          origin_key || '||' || destination_key, current_started_at
      ) on conflict (route_key) do update set
        first_seen_at = least(
          achievement_progress_route_usage.first_seen_at,
          excluded.first_seen_at
        );
    end if;
  select coalesce(max(usage.usage_count), 0)
    into favorite_station_progress
  from pg_temp.achievement_progress_station_usage usage;

  update public.user_achievements achievement
  set progress = greatest(pit_stop_progress, achievement.threshold),
      updated_at = now()
  where achievement.user_id = p_user_id
    and achievement.category_id = 'pit_stops';

  update public.user_achievements achievement
  set progress = greatest(fast_trip_progress, achievement.threshold),
      updated_at = now()
  where achievement.user_id = p_user_id
    and achievement.category_id = 'fast_trips_14_kmh';


  insert into public.user_achievements (
    user_id, category_id, level_id, threshold, unlocked_at, updated_at
  )
  select p_user_id, 'night_trips', level.level_id, level.threshold,
    min(events.ended_at), now()
  from (values
    ('graphite', 1), ('bronze', 10), ('silver', 50), ('gold', 100)
  ) as level(level_id, threshold)
  join (
    select ended_at,
      row_number() over (order by event_index) as progress_value
    from pg_temp.achievement_progress_night_events
  ) events on events.progress_value >= level.threshold
  group by level.level_id, level.threshold
  on conflict (user_id, category_id, level_id) do update set
    threshold = excluded.threshold,
    unlocked_at = least(public.user_achievements.unlocked_at, excluded.unlocked_at),
    updated_at = now();

  insert into public.user_achievements (
    user_id, category_id, level_id, threshold, unlocked_at, updated_at
  )
  select p_user_id, 'explored_routes', level.level_id, level.threshold,
    min(routes.first_seen_at), now()
  from (values
    ('graphite', 10), ('bronze', 50), ('silver', 200), ('gold', 500)
  ) as level(level_id, threshold)
  join (
    select first_seen_at,
      row_number() over (order by first_seen_at, route_key) as progress_value
    from pg_temp.achievement_progress_route_usage
  ) routes on routes.progress_value >= level.threshold
  group by level.level_id, level.threshold
  on conflict (user_id, category_id, level_id) do update set
    threshold = excluded.threshold,
    unlocked_at = least(public.user_achievements.unlocked_at, excluded.unlocked_at),
    updated_at = now();

  update public.user_achievements achievement
  set progress = greatest(night_trip_progress, achievement.threshold), updated_at = now()
  where achievement.user_id = p_user_id and achievement.category_id = 'night_trips';

  select count(*)::integer into explored_route_progress
  from pg_temp.achievement_progress_route_usage;

  update public.user_achievements achievement
  set progress = greatest(explored_route_progress, achievement.threshold), updated_at = now()
  where achievement.user_id = p_user_id and achievement.category_id = 'explored_routes';
  update public.user_achievements achievement
  set progress = greatest(favorite_station_progress, achievement.threshold),
      updated_at = now()
  where achievement.user_id = p_user_id
    and achievement.category_id = 'favorite_station';
end;
$$;
revoke all on function public.refresh_profile_achievement_progress(uuid) from public;

do $$
declare
  existing_profile record;
begin
  for existing_profile in select profile.user_id from public.profiles profile loop
    perform public.refresh_profile_achievements(existing_profile.user_id);
  end loop;
end;
$$;
